<img src="../asset/img/logo-speed.png">
<h3>Unesite novu lozinku</h3>
<form action="#" method="post">
    <label for="password">
        <i class="fas fa-lock"></i>
    </label>
    <input type="password" name="password" placeholder="Nova lozinka" id="password" required>
    <br><br>
    <label for="password">
        <i class="fas fa-lock"></i>
    </label>
    <input type="password" name="cpassword" placeholder="Potvrda lozinke" id="password" required>
    <br><br>
    <input type="submit" value="Promeni lozinku">
    <br>
    <?php
    if (isset($_SESSION['error']) and $message = $_SESSION['error']){
        echo '<div class="message">'.
            $message.
            '<div/>';
        unset($_SESSION['error']);
    }

    if (isset($_SESSION['success']) and $message = $_SESSION['success']){
        echo '<div class="message">'.
            $message.
            '<div/>';
        unset($_SESSION['success']);
    }

    ?>
<div class="buttonforlogin">
    <a href="/login"><i class="fas fa-arrow-left"></i></a>
</div>