<img src="../asset/img/logo-speed.png">
<h3>Unesite e-poštu za resetovanje naloga</h3>
<form action="#" method="post">
    <label for="username">
        <i class="fas fa-user"></i>
    </label>
    <input type="text" name="email" placeholder="Unesite e-poštu" id="username" required>
    <br><br>
    <input type="submit" value="Pošalji">
    <br>
    <?php
    if (isset($_SESSION['error']) and $message = $_SESSION['error']){
        echo '<div class="message">'.
            $message.
            '<div/>';
        unset($_SESSION['error']);
    }

    if (isset($_SESSION['success']) and $message = $_SESSION['success']){
        echo '<div class="message">'.
            $message.
            '<div/>';
        unset($_SESSION['success']);
    }

    ?>
</form>

<div class="buttonforlogin">
    <a href="/login"><i class="fas fa-arrow-left"></i></a>
</div>