<!DOCTYPE html>
<html lang="sr">
<head>
    <meta charset="utf-8">
    <title>Prijavi se - Administracioni panel Rent a car app</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
    <link rel="stylesheet" href="../asset/css/admin.css" type="text/css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,400;0,500;0,600;0,700;1,100;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
</head>
<body>
<div class="login">
    <div class="form">
        <?= $this->content ?>
    </div>
</div>
</body>
</html>

